### PR TITLE
Fix flooding of plugwise network by CircleEnergyCountersRequest

### PR DESCRIPTION
**Pull request by dirixmjm**
While not having traced back fully to the origin this is what was happening:
At some point the current (ongoing) memory slot of the energy counters is being requested repeatedly, flooding the Stick / Network.
(1) On line 611 (original) it is checked whether any CircleEnergyCountersRequest have been sent recently, however this always resolved as true as long as the last request is more recent than 15 minutes using self._energy_history_collecting_timestamp
(2) On line 631 (original) an update CircleEnergyCountersRequest was being sent, however _energy_history_collecting_timestamp was not set.

(1) and (2) are resolved, but (1) requires checking whether was really a mistake or intentional behaviour.

### CODE REVIEW

**Review by CoMPaTech — CHANGES_REQUESTED** [review]
Thanks for your PR @dirixmjm 
as the pre-commit in the PR conversation already shows, lines 631/632 seem wrongly indented. (they should be in line with the comment above and the if statement below)

**Comment by CoMPaTech** [comment]
Unfortunately I didn't spend much time with the USB code so I can't say anything on the intentional behaviour, though I think if @brefra still has no time we can make the effort to (once the code is correct) release an alpha version with the beta component.

**Comment by bouwew** [comment]
@dirixmjm Did you test your updates in a live system?

**Comment by dirixmjm** [comment]
> Thanks for your PR @dirixmjm as the pre-commit in the PR conversation already shows, lines 631/632 seem wrongly indented. (they should be in line with the comment above and the if statement below)

I saw the same, but when I check with the editor (Notepad++) it looks ok. I'll check it again with vim.

**Comment by dirixmjm** [comment]
I'll try again.

**Comment by dirixmjm** [comment]
> @dirixmjm Did you test your updates in a live HA system?

Hi bouwew, yes I am running it live. For now it has stopped flooding my system.

**Pull request closed without merging**
