### PR TITLE
Fix flooding of plugwise network by CircleEnergyCountersRequest (2nd try)

### PR DESCRIPTION
**Pull request by dirixmjm**
See #110 for original attempt
Hi Tom, let's try again.

### CODE REVIEW

**Review by CoMPaTech — APPROVED** [review]
LGTM

**Comment by CoMPaTech** [comment]
As for future, you could have just modified and changed the original PR, but no worries, this works as well.

**Comment by CoMPaTech** [comment]
Mergeable, the CodeFactor issue (finding a TODO) is existing code, ignoring.

**Comment by CoMPaTech** [comment]
@brefra @bouwew  Can't release without merge as this is an incoming PR - so merging and releasing from there (we can always revert)

**Comment by CoMPaTech** [comment]
Little hold on this one (as not all actions have been run and I see @bouwew also tried something looking through the actions).

**Comment by bouwew** [comment]
@dirixmjm You can test your updates by changing the plugwise_usb version to `0.31.1b0` in the `manifest.json` file of the plugwise_usb-beta custom_component in HA.

I've done that just now, the custom_component seems to load and function as before.

**Pull request merged**
