### PR TITLE
Catch up

### PR DESCRIPTION
**Pull request by CoMPaTech**
## Summary by CodeRabbit

- **New Features**
  - Updated CI workflow configurations, improving caching mechanisms and simplifying action versioning.

- **Bug Fixes**
  - Enhanced consistency in commands related to Python package installations and updated linting processes.

- **Documentation**
  - Updated changelog to reflect ongoing updates in the CI process and necessary changes for compatibility with Python 3.12.

- **Refactor**
  - Improved readability and consistency of docstrings across multiple files.
  
- **Chores**
  - Altered installation commands to include a new package requirement, `uv`, in setup scripts.

### CODE REVIEW

**Comment by CoMPaTech** [comment]
@coderabbitai please review again in full, that is, including updating all outdated conversations, they seem legit enough though can't be committed in batch due to the reference being outdated. Thanks in advance

**Comment by CoMPaTech** [comment]
OK, most of the nitpicks by CodeRabbit are ruff anyway, so basically updating each and every doctstring properly. (Which is also why I left ruff out for now, will add an issue to ensure someone picks this up).

As for the red crosses, nothing to see there:
- [x] Black-ing changed some lines, hence the test-coverage dropping (actually there is still no testing
- [x] CodeFactor issues ignored (they are interpreting the GitHub yamls wrong

If this is accepted/merged please tick the LOWEST checkbox on https://github.com/plugwise/python-plugwise-usb/issues/3 (`Check this box to trigger a request for Renovate to run again on this repository`) to see if all other PRs flow through now.

**Comment by CoMPaTech** [comment]
@CodeRabbitAI please approve, your `ruff` remarks are noted through #171 the changelog updates are placeholders anyway. Your timezone suggestions are noted in #173 for followup

**Comment by CoMPaTech** [comment]
Also replaced prettier with biome (see also https://github.com/plugwise/plugwise-beta/pull/695) and missing changelog entry as well as other pre-commit updates. This should supersede #157 and close it as incomplete.

**Review by dirixmjm — COMMENTED** [review]
Looks ok to me

**Review by dirixmjm — APPROVED** [review]
ok

**Pull request merged**
